module: models.content_glide
model:  ContentNet 

soft_mask: False
jitter_ratio: 0.1
grad_clip: 0. 
freeze_transformer: False
freeze_diffusion: True

side_x: 64
resume_ckpt: /home/haoyueliu/project/affordance_diffusion/output/release/content_glide/checkpoints/last.ckpt
